var storyContent = {
  inkVersion: 19,
  root: [
    [
      "^Fjon was a little creature. Cute and a bit spiky. Nothing unusual since Fjon was a hedgehog. Not so normal was the fact that Fjon was able to communicate with people. He literally spoke. His voice was a bit scratchy and high, just like excited children sound. And yes, he himself was a bit excited, too. Fjon was on a mission to become a Codegram pet. Will he reach his dream or will the obstacles be too difficult to overcome?",
      "\n",
      {
        "->": "Hej",
      },
      [
        "done",
        {
          "#n": "g-0",
        },
      ],
      null,
    ],
    "done",
    {
      Hej: [
        [
          {
            "#": "hej",
          },
          "^After kind of a rough night (you had a couple of beers in front of the laptop to celebrate finishing an exciting and challenging project with your colleagues), you're trying to get a clean head wandering around in the nearby forest, when you suddenly hear an ear-piercing tone:",
          "\n",
          '^"Hej you." ',
          {
            "#": "hedge",
          },
          "\n",
          "^You turn around but you don't see anyone.",
          "\n",
          '^"Over here." , says the voice. ',
          {
            "#": "hedge",
          },
          "\n",
          "ev",
          "str",
          "^Check the place again",
          "/str",
          "/ev",
          {
            "*": ".^.c-0",
            flg: 4,
          },
          "ev",
          "str",
          "^Don't check it again",
          "/str",
          "/ev",
          {
            "*": ".^.c-1",
            flg: 4,
          },
          {
            "c-0": [
              "^ ",
              {
                "->": "check_again",
              },
              "\n",
              null,
            ],
            "c-1": [
              "^ ",
              {
                "->": "do_not_check_again",
              },
              "\n",
              null,
            ],
          },
        ],
        null,
      ],
      check_again: [
        {
          "#": "brown_lurking",
        },
        "^You check the surrounding once again but you are alone. Although, something brown-ish is lurking from under that bush on the right side. And at the same time you spot it, the bush is moving and a hedgehog appears. You start to laugh. The hedgehog couldn't be the one who talked to you. So, you are thinking that either you had too many drinks last night or someone is playing a trick on you – when you hear",
        "\n",
        '^"It\'s me, down here." ',
        {
          "#": "hedge",
        },
        "\n",
        "^Okay, not too many drinks. Someone plays a prank. But who?",
        "\n",
        {
          "->": "choose_your_codegrammer",
        },
        null,
      ],
      do_not_check_again: [
        {
          "#": "fall_down",
        },
        "^You don't like this. The headache comes back. So you pretend to not having heard anything and you continue to walk. In the next second, you fall. Too exhausted for fast reactions, your face lands in the mud. When you raise it, you stare in the eyes, or better, nose, of a small hedgehog. He grins. Seriously. The hedgehog is smiling.",
        "\n",
        '^"We could have solved this differently, you know?", he babbles. ',
        {
          "#": "hedge",
        },
        "\n",
        "^You put your face down again. That animal didn't talk to you. It's all in your head. You fell down and hurt your head. You hear a cracking sound from the bushes behind you. You knew it. Someone is playing a prank. But who?",
        "\n",
        {
          "->": "choose_your_codegrammer",
        },
        {
          "#f": 1,
        },
      ],
      choose_your_codegrammer: [
        [
          {
            "#": "codegrammer",
          },
          "ev",
          "str",
          "^Agustí",
          "/str",
          "/ev",
          {
            "*": ".^.c-0",
            flg: 4,
          },
          "ev",
          "str",
          "^Aitor",
          "/str",
          "/ev",
          {
            "*": ".^.c-1",
            flg: 4,
          },
          "ev",
          "str",
          "^Andrea",
          "/str",
          "/ev",
          {
            "*": ".^.c-2",
            flg: 4,
          },
          "ev",
          "str",
          "^Arnau",
          "/str",
          "/ev",
          {
            "*": ".^.c-3",
            flg: 4,
          },
          "ev",
          "str",
          "^David",
          "/str",
          "/ev",
          {
            "*": ".^.c-4",
            flg: 4,
          },
          "ev",
          "str",
          "^Dasha",
          "/str",
          "/ev",
          {
            "*": ".^.c-5",
            flg: 4,
          },
          "ev",
          "str",
          "^Marc D.",
          "/str",
          "/ev",
          {
            "*": ".^.c-6",
            flg: 4,
          },
          "ev",
          "str",
          "^Edgar",
          "/str",
          "/ev",
          {
            "*": ".^.c-7",
            flg: 4,
          },
          "ev",
          "str",
          "^Eva",
          "/str",
          "/ev",
          {
            "*": ".^.c-8",
            flg: 4,
          },
          "ev",
          "str",
          "^Georgi",
          "/str",
          "/ev",
          {
            "*": ".^.c-9",
            flg: 4,
          },
          "ev",
          "str",
          "^Hugo",
          "/str",
          "/ev",
          {
            "*": ".^.c-10",
            flg: 4,
          },
          "ev",
          "str",
          "^Josep",
          "/str",
          "/ev",
          {
            "*": ".^.c-11",
            flg: 4,
          },
          "ev",
          "str",
          "^Leo",
          "/str",
          "/ev",
          {
            "*": ".^.c-12",
            flg: 4,
          },
          "ev",
          "str",
          "^Marina",
          "/str",
          "/ev",
          {
            "*": ".^.c-13",
            flg: 4,
          },
          "ev",
          "str",
          "^Marc R.",
          "/str",
          "/ev",
          {
            "*": ".^.c-14",
            flg: 4,
          },
          "ev",
          "str",
          "^Nick",
          "/str",
          "/ev",
          {
            "*": ".^.c-15",
            flg: 4,
          },
          "ev",
          "str",
          "^Oriol",
          "/str",
          "/ev",
          {
            "*": ".^.c-16",
            flg: 4,
          },
          "ev",
          "str",
          "^Svenja",
          "/str",
          "/ev",
          {
            "*": ".^.c-17",
            flg: 4,
          },
          "ev",
          "str",
          "^Txus",
          "/str",
          "/ev",
          {
            "*": ".^.c-18",
            flg: 4,
          },
          "ev",
          "str",
          "^Vero",
          "/str",
          "/ev",
          {
            "*": ".^.c-19",
            flg: 4,
          },
          {
            "c-0": [
              "\n",
              "ev",
              "str",
              "^Agustí",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-1": [
              "\n",
              "ev",
              "str",
              "^Aitor",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-2": [
              "\n",
              "ev",
              "str",
              "^Andrea",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-3": [
              "\n",
              "ev",
              "str",
              "^Arnau",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-4": [
              "\n",
              "ev",
              "str",
              "^David",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-5": [
              "\n",
              "ev",
              "str",
              "^Dasha",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-6": [
              "\n",
              "ev",
              "str",
              "^Marc D.",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-7": [
              "\n",
              "ev",
              "str",
              "^Edgar",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-8": [
              "\n",
              "ev",
              "str",
              "^Eva",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-9": [
              "\n",
              "ev",
              "str",
              "^Georgi",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-10": [
              "\n",
              "ev",
              "str",
              "^Hugo",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-11": [
              "\n",
              "ev",
              "str",
              "^Josep",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-12": [
              "\n",
              "ev",
              "str",
              "^Leo",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-13": [
              "\n",
              "ev",
              "str",
              "^Marina",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-14": [
              "\n",
              "ev",
              "str",
              "^Marc R.",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-15": [
              "\n",
              "ev",
              "str",
              "^Nick",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-16": [
              "\n",
              "ev",
              "str",
              "^Oriol",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-17": [
              "\n",
              "ev",
              "str",
              "^Svenja",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-18": [
              "\n",
              "ev",
              "str",
              "^Txus",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
            "c-19": [
              "\n",
              "ev",
              "str",
              "^Vero",
              "/str",
              "/ev",
              {
                "->": "hedgehogs_can_speak",
              },
              null,
            ],
          },
        ],
        null,
      ],
      hedgehogs_can_speak: [
        {
          "temp=": "guiltyCodegrammer",
        },
        [
          {
            "#": "choosen",
          },
          "^The hedgehog looked grumpy.",
          "\n",
          '^"You really believe ',
          "ev",
          {
            "VAR?": "guiltyCodegrammer",
          },
          "out",
          "/ev",
          "^ would do that? Don't you know that Hedgehogs can talk - IF THEY decide to let YOU hear them?\" ",
          {
            "#": "hedge",
          },
          "\n",
          "^And with that, the hedgehog comes a little bit closer.",
          "\n",
          '^"I\'m Fjon, by the way.", he says. ',
          {
            "#": "hedge",
          },
          "\n",
          "ev",
          "str",
          "^You stay where you are",
          "/str",
          "/ev",
          {
            "*": ".^.c-0",
            flg: 20,
          },
          "ev",
          "str",
          "^You leave",
          "/str",
          "/ev",
          {
            "*": ".^.c-1",
            flg: 20,
          },
          {
            "c-0": [
              "^ ",
              {
                "->": "stay_and_sit_down",
              },
              "\n",
              {
                "#f": 5,
              },
            ],
            "c-1": [
              "^ ",
              {
                "->": "hurry",
              },
              "\n",
              {
                "#f": 5,
              },
            ],
          },
        ],
        null,
      ],
      stay_and_sit_down: [
        [
          {
            "#": "sit_down",
          },
          "^It's too much for your nerves (and headache), so you sit down. Fjon crawls to your legs, climbs on your right one and finds himself an obvious comfortable position. He starts talking again:",
          "\n",
          '^"You know, it\'s actually pretty amazing to meet you here. I was on the way to your office but that was a bit tricky with the whole remote thingy. The reason, I was looking for you, well, not specifically you, but any Codegrammer, no offence, is that I heard so much about your pets. They even have their own room in the wide world web. And I, ... I want to become a Codegram pet as well." ',
          {
            "#": "hedge",
          },
          "\n",
          "^He looked as if he was waiting for an answer.",
          "\n",
          "ev",
          "str",
          "^You give him an answer",
          "/str",
          "/ev",
          {
            "*": ".^.c-0",
            flg: 20,
          },
          "ev",
          "str",
          "^You say nothing",
          "/str",
          "/ev",
          {
            "*": ".^.c-1",
            flg: 20,
          },
          {
            "c-0": [
              "^ ",
              {
                "->": "give_answer",
              },
              "\n",
              {
                "#f": 5,
              },
            ],
            "c-1": [
              "^ ",
              {
                "->": "give_no_answer",
              },
              "\n",
              {
                "#f": 5,
              },
            ],
          },
        ],
        null,
      ],
      hurry: [
        {
          "#": "hurry",
        },
        "ev",
        {
          "CNT?": "do_not_check_again",
        },
        "/ev",
        [
          {
            "->": ".^.b",
            c: true,
          },
          {
            b: [
              "\n",
              "^Carefully not to fall again, you turn around and walk slowly in the direction you came from.",
              "\n",
              '^"Are you still mad, that I put that tree branch in front of you? I won\'t hurt you ever again. Just hear me out, pleeeease." ',
              {
                "#": "hedge",
              },
              "\n",
              "^This is getting really creepy. A speaking hedgehog.",
              "\n",
              {
                "->": "stay_and_sit_down",
              },
              {
                "->": "hurry.5",
              },
              null,
            ],
          },
        ],
        "nop",
        "\n",
        "ev",
        {
          "CNT?": "do_not_check_again",
        },
        "!",
        "/ev",
        [
          {
            "->": ".^.b",
            c: true,
          },
          {
            b: [
              "\n",
              "^You turn around and walk slowly in the direction you came from.",
              "\n",
              '^"Why are you running away? I did decide to let you hear me and you still don\'t believe me? See, I can jump and roll on my back." ',
              {
                "#": "hedge",
              },
              "\n",
              "^You turn around and it's exactly the way he said it is. A hedgehog jumping around, not very high tho and rolling around.",
              "\n",
              {
                "->": "stay_and_sit_down",
              },
              {
                "->": "hurry.12",
              },
              null,
            ],
          },
        ],
        "nop",
        "\n",
        null,
      ],
      give_answer: [
        {
          "#": "help",
        },
        "^Still confused about the fact that you are sitting in the forest with a hedgehog named Fjon on your legs, you hear yourself asking:",
        "\n",
        '^"And how can I help you becoming a codegram pet?".',
        "\n",
        {
          "->": "explanation",
        },
        null,
      ],
      give_no_answer: [
        {
          "#": "no_answer",
        },
        '^You look at him and wait. "Did you hear me?" You still don\'t answer.',
        "\n",
        '^"Don\'t you like animals? Although, no, that is not possible. Everybody at Codegram loves animals, am I right?" ',
        {
          "#": "hedge",
        },
        "\n",
        '^The hedgehog jumps down from your leg and rolls on his back. You reach out to tickle the little creature. Fjon starts to laugh. So do you and after a little while, you hear yourself asking: "Okay, little guy, how can I help you?"',
        "\n",
        {
          "->": "explanation",
        },
        null,
      ],
      explanation: [
        [
          '^"Nothing easier than that. You can adopt me!". ',
          {
            "#": "hedge",
          },
          "\n",
          "^Fjon jumps down from your leg on the earthy path and runs excitedly from left to right and back.",
          "\n",
          '^"I promise. I\'ll be suuuuuper nice and I will never use my quills to hurt you. Big hedgehog promise!" ',
          {
            "#": "hedge",
          },
          "\n",
          "^Fjon stops and looks at you with big eyes, well as big as Hedgehog eyes can be.",
          "\n",
          "ev",
          "str",
          "^You adopt Fjon",
          "/str",
          "/ev",
          {
            "*": ".^.c-0",
            flg: 20,
          },
          "ev",
          "str",
          "^You ask Svenja to adopt him",
          "/str",
          "/ev",
          {
            "*": ".^.c-1",
            flg: 20,
          },
          {
            "c-0": [
              "^ ",
              {
                "->": "adopt_fjon",
              },
              "\n",
              {
                "#f": 5,
              },
            ],
            "c-1": [
              "^ ",
              {
                "->": "ask_svenja_to_adopt",
              },
              "\n",
              {
                "#f": 5,
              },
            ],
          },
        ],
        null,
      ],
      adopt_fjon: [
        {
          "#": "adopt_fjon",
        },
        "^In these complicated times, it's always nice to have a friend by your side. And Fjon was right, working remotely can make you feel lonely from time to time. At least, if you don't have such a wonderful team like you have at Codegram. And Fjon, with his funny voice, would just fit perfectly to Bimo, Boira and Black, Juanita and Luna and Yoko and maybe even Ona. You won't let him near Hugo tho. That's for sure. And with these thought, you pick him up and carry him home where you'll send cute pictures to the 'ot-pet' channel and a day later, the hedgehog Fjon has his own page in the wide world web.",
        "\n",
        "end",
        null,
      ],
      ask_svenja_to_adopt: [
        {
          "#": "svenja_adoption",
        },
        "^While it's true that you kinda became fond of this little thingy, you don't have time for a hedgehog right now. But you are sure that Svenja would take him in. So, you say to Fjon: \"Don't worry. I'll take care of you. Unfortunately, you can't become my pet but I'll visit you super often and we'll sea each other in our Friday group calls because pets are welcome every time, everywhere. I'll take you to Svenja – she has two adorable dogs: Ona and Hugo. She'll be happy to give you a new home.\" Fjon smiles. You pick him up and carry him to Svenja.",
        "\n",
        {
          "->": "epilogue",
        },
        null,
      ],
      epilogue: [
        {
          "#": "epilogue",
        },
        "^EPILOGUE",
        "\n",
        "^Sadly, you forgot Hugos' manner and his special taste for cats and hedgehogs. The day you left him in Svenjas' hands was the last day you saw Fjon alive.",
        "\n",
        "end",
        null,
      ],
      "global decl": [
        "ev",
        1,
        {
          "VAR=": "headache",
        },
        "/ev",
        "end",
        null,
      ],
    },
  ],
  listDefs: {},
};
